### ISSUE TITLE
Auth0 rules environment has module property

### ISSUE THREAD

**Issue by chandern** [KleeUT/Auth0-rules-cicd-example-2020#1]
Hi, I was going through your blog on using CI and CD for managing auth0 rules. It's clever to be able to use the if check on module to differentiate between test run and running on auth0 tenant UI. However I think the module property now exists as it is trying to set module.exports when trying to test my rule on the UI and I get the following error:
`ERROR: Cannot read property 'apply' of undefined`
I know you haven't looked at this in some time but have you come across this?

**Comment by KleeUT** [comment]
@chandern I haven't come across it, but I was able to reproduce it this morning using one of my tenants. Thanks for the comment, I have production workloads using this method that I'll need to look into. They're not failing now but they could well start.

**Comment by chandern** [comment]
No worries. FYI I've come across some Auth0 documentation on testing rules best practices for a CI/CD flow that you may find useful. https://auth0.com/docs/best-practices/rules-testing-best-practices
Seems fine for my testing purposes. I will close this issue
